name: tests

on: [push, pull_request, workflow_dispatch]

jobs:

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            .github/workflows/main.yml
            requirements.dev.txt

      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.dev.txt

      - run: flake8 .

      - run: pytest

      - run: mypy .

      - name: cli
        if: runner.os != 'Windows'
        run: |
          python -m build -n -w
          cd dist
          pip install *.whl
          pylnk3 create --help
          python -m pylnk3 create --help

  release:
    needs:
      - tests
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: |
            .github/workflows/main.yml
            requirements.dev.txt

      - name: dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.dev.txt

      - run: python -m build -n

      - run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
